import { useEffect, useState } from "react";
import { Bike, CheckCircle2, LogOut, Phone, Save, UserRound } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { supabase } from "../../lib/supabase";
import CourierShell from "../../components/CourierShell";

export default function CourierProfile() {
  const navigate = useNavigate(); const [name,setName]=useState(""); const [phone,setPhone]=useState(""); const [vehicle,setVehicle]=useState("bike"); const [saved,setSaved]=useState(false);
  useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser(); if(!user)return; const [{data:profile},{data:application}]=await Promise.all([supabase.from("profiles").select("full_name,phone").eq("id",user.id).single(),supabase.from("courier_applications").select("vehicle_type").eq("user_id",user.id).single()]); setName(profile?.full_name||""); setPhone(profile?.phone||""); setVehicle(application?.vehicle_type||"bike");})();},[]);
  const save=async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user)return;await Promise.all([supabase.from("profiles").update({full_name:name.trim(),phone:phone.trim()}).eq("id",user.id),supabase.from("courier_applications").update({vehicle_type:vehicle}).eq("user_id",user.id)]);setSaved(true);setTimeout(()=>setSaved(false),1800);};
  const logout=async()=>{await supabase.auth.signOut();navigate("/auth");};
  return <CourierShell title="Mon profil" back="/courier"><section className="rounded-[2rem] border border-foodiz-gold/20 bg-[linear-gradient(145deg,rgba(216,168,79,0.15),rgba(17,17,17,0.97)_40%)] p-6 text-center"><div className="w-20 h-20 mx-auto rounded-[1.8rem] bg-foodiz-gold/10 border border-foodiz-gold/20 flex items-center justify-center shadow-[0_0_40px_rgba(216,168,79,0.12)]"><UserRound size={34} className="text-foodiz-gold" /></div><h2 className="foodiz-title text-2xl mt-4">{name||"Livreur Foodiz"}</h2><p className="text-xs text-foodiz-gray mt-2">Votre identité professionnelle</p></section><section className="foodiz-card p-5 mt-4 space-y-4"><label className="block"><span className="text-[10px] uppercase tracking-widest text-foodiz-gold">Nom complet</span><div className="mt-2 flex items-center gap-3 rounded-2xl border border-white/10 bg-white/[0.03] px-4"><UserRound size={17} className="text-foodiz-gold" /><input value={name} onChange={e=>setName(e.target.value)} className="w-full bg-transparent py-4 text-foodiz-cream outline-none" /></div></label><label className="block"><span className="text-[10px] uppercase tracking-widest text-foodiz-gold">Téléphone</span><div className="mt-2 flex items-center gap-3 rounded-2xl border border-white/10 bg-white/[0.03] px-4"><Phone size={17} className="text-foodiz-gold" /><input value={phone} onChange={e=>setPhone(e.target.value)} className="w-full bg-transparent py-4 text-foodiz-cream outline-none" /></div></label><label className="block"><span className="text-[10px] uppercase tracking-widest text-foodiz-gold">Véhicule</span><div className="mt-2 flex items-center gap-3 rounded-2xl border border-white/10 bg-white/[0.03] px-4"><Bike size={17} className="text-foodiz-gold" /><select value={vehicle} onChange={e=>setVehicle(e.target.value)} className="w-full bg-transparent py-4 text-foodiz-cream outline-none"><option className="bg-foodiz-card" value="bike">Vélo</option><option className="bg-foodiz-card" value="scooter">Scooter</option><option className="bg-foodiz-card" value="motorcycle">Moto</option><option className="bg-foodiz-card" value="car">Voiture</option></select></div></label><button onClick={save} className="foodiz-btn w-full py-4 flex items-center justify-center gap-2">{saved?<><CheckCircle2 size={18}/>Enregistré</>:<><Save size={18}/>Enregistrer</>}</button></section><button onClick={logout} className="w-full mt-4 rounded-2xl border border-foodiz-red/20 bg-foodiz-red/5 p-4 text-foodiz-red flex items-center justify-center gap-2"><LogOut size={17}/>Se déconnecter</button></CourierShell>;
}
