import { useEffect, useMemo, useState } from "react";
import { Bike, CalendarDays, Coins } from "lucide-react";
import { supabase } from "../../lib/supabase";
import CourierShell from "../../components/CourierShell";

export default function CourierRevenues() {
  const [orders, setOrders] = useState<any[]>([]);
  useEffect(() => { (async () => { const { data: { user } } = await supabase.auth.getUser(); if (!user) return; const { data } = await supabase.from("orders").select("id, delivered_at, delivery_fee_cents, courier_earnings_cents, courier_prime_fund_cents, courier_delay_penalty_cents, restaurant:restaurants(name)").eq("courier_id", user.id).eq("status", "delivered").order("delivered_at", { ascending: false }); setOrders(data || []); })(); }, []);
  const stats = useMemo(() => { const now = new Date(); const day = new Date(); day.setHours(0,0,0,0); const week = new Date(now.getTime() - 7*86400000); const amount = (items:any[]) => items.reduce((sum,item)=>sum+(item.delivery_fee_cents||0)+(item.courier_earnings_cents||0)+(item.courier_prime_fund_cents||0)-(item.courier_delay_penalty_cents||0),0)/100; return { day: amount(orders.filter(o=>new Date(o.delivered_at)>=day)), week: amount(orders.filter(o=>new Date(o.delivered_at)>=week)), total: amount(orders) }; }, [orders]);
  return <CourierShell title="Mes gains" back="/courier"><section className="rounded-[2rem] border border-foodiz-gold/20 bg-[linear-gradient(145deg,rgba(216,168,79,0.18),rgba(17,17,17,0.96)_42%)] p-6"><p className="text-[10px] uppercase tracking-[0.2em] text-foodiz-gold">Total gagné</p><p className="text-4xl font-serif italic text-foodiz-cream mt-3">{stats.total.toFixed(2)} €</p><p className="text-xs text-foodiz-gray mt-2">Montants nets après les éventuels ajustements de retard audités.</p></section><section className="grid grid-cols-2 gap-3 mt-4"><div className="foodiz-card p-5"><Coins size={18} className="text-foodiz-green" /><p className="text-2xl text-foodiz-green font-serif mt-4">{stats.day.toFixed(2)} €</p><p className="text-[10px] text-foodiz-gray mt-1">Aujourd'hui</p></div><div className="foodiz-card p-5"><CalendarDays size={18} className="text-foodiz-gold" /><p className="text-2xl text-foodiz-cream font-serif mt-4">{stats.week.toFixed(2)} €</p><p className="text-[10px] text-foodiz-gray mt-1">7 derniers jours</p></div></section><div className="mt-4 space-y-3">{orders.slice(0,10).map(order=><div key={order.id} className="foodiz-card p-4 flex items-center gap-3"><div className="w-10 h-10 rounded-xl bg-foodiz-gold/10 flex items-center justify-center"><Bike size={17} className="text-foodiz-gold" /></div><div className="flex-1"><p className="text-sm text-foodiz-cream">{order.restaurant?.name || "Livraison Foodiz"}</p><p className="text-[10px] text-foodiz-gray mt-1">{new Date(order.delivered_at).toLocaleString("fr-FR")}</p>{order.courier_delay_penalty_cents > 0 && <p className="mt-1 text-[10px] text-foodiz-red">Retard : -{(order.courier_delay_penalty_cents/100).toFixed(2)} €</p>}</div><p className="text-foodiz-green">+{(((order.delivery_fee_cents||0)+(order.courier_earnings_cents||0)+(order.courier_prime_fund_cents||0)-(order.courier_delay_penalty_cents||0))/100).toFixed(2)} €</p></div>)}</div></CourierShell>;
}
