-- Weello pre-launch mode:
-- - public launch status;
-- - Auth-linked pre-registrations;
-- - admin-only global visibility;
-- - restrictive access gate for every existing application table.

CREATE TABLE IF NOT EXISTS public.app_settings (
  key text PRIMARY KEY,
  value jsonb NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO public.app_settings (key, value)
VALUES ('launch_status', '{"launched": false}'::jsonb)
ON CONFLICT (key) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.prelaunch_profiles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  role text NOT NULL CHECK (role IN ('client', 'livreur', 'partenaire')),
  first_name text NOT NULL,
  last_name text NOT NULL,
  email text NOT NULL,
  phone text NOT NULL,
  city text NOT NULL,
  status text NOT NULL DEFAULT 'prelaunch_pending'
    CHECK (status IN ('prelaunch_pending', 'launch_email_sent', 'activated', 'rejected')),
  marketing_consent boolean NOT NULL DEFAULT false,
  consent_at timestamptz,
  launch_token text UNIQUE,
  launch_token_expires_at timestamptz,
  launch_notified_at timestamptz,
  activated_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS prelaunch_profiles_email_unique_ci
  ON public.prelaunch_profiles (lower(email));

CREATE INDEX IF NOT EXISTS prelaunch_profiles_status_idx
  ON public.prelaunch_profiles (status, created_at);

CREATE TABLE IF NOT EXISTS public.prelaunch_partner_details (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  prelaunch_profile_id uuid NOT NULL UNIQUE
    REFERENCES public.prelaunch_profiles(id) ON DELETE CASCADE,
  establishment_name text NOT NULL,
  establishment_type text NOT NULL
    CHECK (establishment_type IN ('restaurant', 'market', 'epicerie', 'autre')),
  siret text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.prelaunch_driver_details (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  prelaunch_profile_id uuid NOT NULL UNIQUE
    REFERENCES public.prelaunch_profiles(id) ON DELETE CASCADE,
  vehicle_type text NOT NULL
    CHECK (vehicle_type IN ('velo', 'scooter', 'voiture', 'autre')),
  availability text NOT NULL
    CHECK (availability IN ('journee', 'soiree', 'nuit', 'week_end')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Server-only anti-abuse ledger. No client policy is intentionally granted.
CREATE TABLE IF NOT EXISTS public.prelaunch_registration_attempts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fingerprint_hash text NOT NULL,
  email_hash text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS prelaunch_registration_attempts_lookup_idx
  ON public.prelaunch_registration_attempts (fingerprint_hash, created_at DESC);

CREATE OR REPLACE FUNCTION public.set_prelaunch_updated_at()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS set_prelaunch_profiles_updated_at ON public.prelaunch_profiles;
CREATE TRIGGER set_prelaunch_profiles_updated_at
BEFORE UPDATE ON public.prelaunch_profiles
FOR EACH ROW EXECUTE FUNCTION public.set_prelaunch_updated_at();

DROP TRIGGER IF EXISTS set_prelaunch_partner_details_updated_at ON public.prelaunch_partner_details;
CREATE TRIGGER set_prelaunch_partner_details_updated_at
BEFORE UPDATE ON public.prelaunch_partner_details
FOR EACH ROW EXECUTE FUNCTION public.set_prelaunch_updated_at();

DROP TRIGGER IF EXISTS set_prelaunch_driver_details_updated_at ON public.prelaunch_driver_details;
CREATE TRIGGER set_prelaunch_driver_details_updated_at
BEFORE UPDATE ON public.prelaunch_driver_details
FOR EACH ROW EXECUTE FUNCTION public.set_prelaunch_updated_at();

ALTER TABLE public.app_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.prelaunch_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.prelaunch_partner_details ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.prelaunch_driver_details ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.prelaunch_registration_attempts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "app_settings_public_read" ON public.app_settings;
CREATE POLICY "app_settings_public_read"
ON public.app_settings FOR SELECT
TO anon, authenticated
USING (key = 'launch_status');

DROP POLICY IF EXISTS "app_settings_admin_update" ON public.app_settings;
CREATE POLICY "app_settings_admin_update"
ON public.app_settings FOR UPDATE
TO authenticated
USING (public.current_user_has_role('admin'))
WITH CHECK (public.current_user_has_role('admin'));

DROP POLICY IF EXISTS "prelaunch_profiles_read_own_or_admin" ON public.prelaunch_profiles;
CREATE POLICY "prelaunch_profiles_read_own_or_admin"
ON public.prelaunch_profiles FOR SELECT
TO authenticated
USING (user_id = auth.uid() OR public.current_user_has_role('admin'));

DROP POLICY IF EXISTS "prelaunch_profiles_update_own_or_admin" ON public.prelaunch_profiles;
CREATE POLICY "prelaunch_profiles_update_own_or_admin"
ON public.prelaunch_profiles FOR UPDATE
TO authenticated
USING (user_id = auth.uid() OR public.current_user_has_role('admin'))
WITH CHECK (
  (user_id = auth.uid() AND status IN ('prelaunch_pending', 'launch_email_sent'))
  OR public.current_user_has_role('admin')
);

DROP POLICY IF EXISTS "prelaunch_partner_details_read_own_or_admin" ON public.prelaunch_partner_details;
CREATE POLICY "prelaunch_partner_details_read_own_or_admin"
ON public.prelaunch_partner_details FOR SELECT
TO authenticated
USING (
  public.current_user_has_role('admin')
  OR EXISTS (
    SELECT 1 FROM public.prelaunch_profiles profile
    WHERE profile.id = prelaunch_profile_id AND profile.user_id = auth.uid()
  )
);

DROP POLICY IF EXISTS "prelaunch_partner_details_update_own_or_admin" ON public.prelaunch_partner_details;
CREATE POLICY "prelaunch_partner_details_update_own_or_admin"
ON public.prelaunch_partner_details FOR UPDATE
TO authenticated
USING (
  public.current_user_has_role('admin')
  OR EXISTS (
    SELECT 1 FROM public.prelaunch_profiles profile
    WHERE profile.id = prelaunch_profile_id AND profile.user_id = auth.uid()
  )
)
WITH CHECK (
  public.current_user_has_role('admin')
  OR EXISTS (
    SELECT 1 FROM public.prelaunch_profiles profile
    WHERE profile.id = prelaunch_profile_id AND profile.user_id = auth.uid()
  )
);

DROP POLICY IF EXISTS "prelaunch_driver_details_read_own_or_admin" ON public.prelaunch_driver_details;
CREATE POLICY "prelaunch_driver_details_read_own_or_admin"
ON public.prelaunch_driver_details FOR SELECT
TO authenticated
USING (
  public.current_user_has_role('admin')
  OR EXISTS (
    SELECT 1 FROM public.prelaunch_profiles profile
    WHERE profile.id = prelaunch_profile_id AND profile.user_id = auth.uid()
  )
);

DROP POLICY IF EXISTS "prelaunch_driver_details_update_own_or_admin" ON public.prelaunch_driver_details;
CREATE POLICY "prelaunch_driver_details_update_own_or_admin"
ON public.prelaunch_driver_details FOR UPDATE
TO authenticated
USING (
  public.current_user_has_role('admin')
  OR EXISTS (
    SELECT 1 FROM public.prelaunch_profiles profile
    WHERE profile.id = prelaunch_profile_id AND profile.user_id = auth.uid()
  )
)
WITH CHECK (
  public.current_user_has_role('admin')
  OR EXISTS (
    SELECT 1 FROM public.prelaunch_profiles profile
    WHERE profile.id = prelaunch_profile_id AND profile.user_id = auth.uid()
  )
);

CREATE OR REPLACE FUNCTION public.foodiz_app_is_launched()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT coalesce(
    (SELECT (value ->> 'launched')::boolean
     FROM public.app_settings
     WHERE key = 'launch_status'),
    false
  );
$$;

CREATE OR REPLACE FUNCTION public.foodiz_application_access_allowed()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT
    public.current_user_has_role('admin')
    OR (
      public.foodiz_app_is_launched()
      AND (
        NOT EXISTS (
          SELECT 1
          FROM public.prelaunch_profiles
          WHERE user_id = auth.uid()
        )
        OR EXISTS (
          SELECT 1
          FROM public.prelaunch_profiles
          WHERE user_id = auth.uid()
            AND status = 'activated'
        )
      )
    );
$$;

REVOKE ALL ON FUNCTION public.foodiz_app_is_launched() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.foodiz_application_access_allowed() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.foodiz_app_is_launched() TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.foodiz_application_access_allowed() TO anon, authenticated, service_role;

-- A restrictive policy is combined with every existing permissive policy.
-- It blocks anonymous and authenticated application data access before launch,
-- while service_role keeps its normal RLS bypass for controlled server routes.
DO $$
DECLARE
  target record;
BEGIN
  FOR target IN
    SELECT namespace.nspname AS schemaname, relation.relname AS tablename
    FROM pg_class relation
    JOIN pg_namespace namespace ON namespace.oid = relation.relnamespace
    WHERE namespace.nspname = 'public'
      AND relation.relkind = 'r'
      AND relation.relrowsecurity = true
      AND relation.relname NOT IN (
        'app_settings',
        'prelaunch_profiles',
        'prelaunch_partner_details',
        'prelaunch_driver_details',
        'prelaunch_registration_attempts'
      )
  LOOP
    EXECUTE format(
      'DROP POLICY IF EXISTS %I ON %I.%I',
      'foodiz_prelaunch_global_gate',
      target.schemaname,
      target.tablename
    );
    EXECUTE format(
      'CREATE POLICY %I ON %I.%I AS RESTRICTIVE FOR ALL TO anon, authenticated USING (public.foodiz_application_access_allowed()) WITH CHECK (public.foodiz_application_access_allowed())',
      'foodiz_prelaunch_global_gate',
      target.schemaname,
      target.tablename
    );
  END LOOP;
END;
$$;
