-- Secure courier document collection and review.
-- Documents remain in a private Storage bucket and are never exposed through
-- public URLs. Only short-lived signed URLs generated by trusted server code
-- may be used to upload or inspect them.

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'courier-documents',
  'courier-documents',
  false,
  8388608,
  ARRAY['image/jpeg', 'image/png', 'application/pdf']
)
ON CONFLICT (id) DO UPDATE SET
  public = false,
  file_size_limit = EXCLUDED.file_size_limit,
  allowed_mime_types = EXCLUDED.allowed_mime_types;

ALTER TABLE public.prelaunch_driver_details
  ADD COLUMN IF NOT EXISTS legal_name text,
  ADD COLUMN IF NOT EXISTS address text,
  ADD COLUMN IF NOT EXISTS postal_code text,
  ADD COLUMN IF NOT EXISTS document_review_status text NOT NULL DEFAULT 'documents_required',
  ADD COLUMN IF NOT EXISTS document_review_comment text,
  ADD COLUMN IF NOT EXISTS document_upload_token_hash text,
  ADD COLUMN IF NOT EXISTS document_upload_token_expires_at timestamptz,
  ADD COLUMN IF NOT EXISTS documents_submitted_at timestamptz,
  ADD COLUMN IF NOT EXISTS reviewed_by uuid REFERENCES public.profiles(id),
  ADD COLUMN IF NOT EXISTS reviewed_at timestamptz;

ALTER TABLE public.prelaunch_driver_details
  DROP CONSTRAINT IF EXISTS prelaunch_driver_details_document_review_status_check,
  DROP CONSTRAINT IF EXISTS prelaunch_driver_details_postal_code_check;

ALTER TABLE public.prelaunch_driver_details
  ADD CONSTRAINT prelaunch_driver_details_document_review_status_check
    CHECK (document_review_status IN (
      'documents_required',
      'pending_review',
      'replacement_requested',
      'approved',
      'rejected'
    )),
  ADD CONSTRAINT prelaunch_driver_details_postal_code_check
    CHECK (postal_code IS NULL OR postal_code ~ '^[0-9]{5}$');

CREATE UNIQUE INDEX IF NOT EXISTS prelaunch_driver_document_upload_token_unique
  ON public.prelaunch_driver_details (document_upload_token_hash)
  WHERE document_upload_token_hash IS NOT NULL;

ALTER TABLE public.courier_applications
  ADD COLUMN IF NOT EXISTS document_review_status text NOT NULL DEFAULT 'documents_required',
  ADD COLUMN IF NOT EXISTS document_review_comment text,
  ADD COLUMN IF NOT EXISTS identity_name_confirmed boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS business_identity_confirmed boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS reviewed_by uuid REFERENCES public.profiles(id),
  ADD COLUMN IF NOT EXISTS reviewed_at timestamptz,
  ADD COLUMN IF NOT EXISTS dispatch_priority_score integer NOT NULL DEFAULT 100;

ALTER TABLE public.courier_applications
  DROP CONSTRAINT IF EXISTS courier_applications_document_review_status_check,
  DROP CONSTRAINT IF EXISTS courier_applications_dispatch_priority_score_check;

ALTER TABLE public.courier_applications
  ADD CONSTRAINT courier_applications_document_review_status_check
    CHECK (document_review_status IN (
      'documents_required',
      'pending_review',
      'replacement_requested',
      'approved',
      'rejected'
    )),
  ADD CONSTRAINT courier_applications_dispatch_priority_score_check
    CHECK (dispatch_priority_score BETWEEN 0 AND 100);

-- Preserve already validated couriers. The mandatory document workflow applies
-- to every new validation and to any previously validated account that must be
-- reviewed again after suspension.
UPDATE public.courier_applications
SET document_review_status = 'approved',
    identity_name_confirmed = true,
    business_identity_confirmed = true
WHERE status = 'validated'
  AND document_review_status = 'documents_required';

CREATE TABLE IF NOT EXISTS public.courier_documents (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  prelaunch_profile_id uuid REFERENCES public.prelaunch_profiles(id) ON DELETE SET NULL,
  document_type text NOT NULL
    CHECK (document_type IN ('identity_front', 'identity_back', 'activity_proof')),
  storage_path text NOT NULL UNIQUE,
  original_name text NOT NULL,
  mime_type text NOT NULL CHECK (mime_type IN ('image/jpeg', 'image/png', 'application/pdf')),
  size_bytes integer NOT NULL CHECK (size_bytes > 0 AND size_bytes <= 8388608),
  status text NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'approved', 'rejected', 'replacement_requested')),
  review_comment text,
  reviewed_by uuid REFERENCES public.profiles(id),
  reviewed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, document_type)
);

CREATE INDEX IF NOT EXISTS courier_documents_review_idx
  ON public.courier_documents (status, created_at DESC);

ALTER TABLE public.courier_documents ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "courier_documents_select_own_or_admin" ON public.courier_documents;
CREATE POLICY "courier_documents_select_own_or_admin"
ON public.courier_documents
FOR SELECT
TO authenticated
USING (
  user_id = auth.uid()
  OR public.current_user_has_role('admin')
);

-- No INSERT/UPDATE/DELETE policy is intentionally granted. Mutations are
-- performed by audited server endpoints using the service role.

DROP TRIGGER IF EXISTS set_courier_documents_updated_at ON public.courier_documents;
CREATE TRIGGER set_courier_documents_updated_at
BEFORE UPDATE ON public.courier_documents
FOR EACH ROW EXECUTE FUNCTION public.set_prelaunch_updated_at();

CREATE OR REPLACE FUNCTION public.require_courier_legal_identity()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
DECLARE
  approved_document_count integer;
BEGIN
  IF NEW.status = 'validated' AND OLD.status IS DISTINCT FROM 'validated' THEN
    SELECT count(*)
    INTO approved_document_count
    FROM public.courier_documents document
    WHERE document.user_id = NEW.user_id
      AND document.status = 'approved'
      AND document.document_type IN ('identity_front', 'identity_back', 'activity_proof');

    IF nullif(trim(coalesce(NEW.legal_name, '')), '') IS NULL
      OR NEW.siret !~ '^[0-9]{14}$'
      OR nullif(trim(coalesce(NEW.address, '')), '') IS NULL
      OR NEW.postal_code !~ '^[0-9]{5}$'
      OR NEW.document_review_status <> 'approved'
      OR NEW.identity_name_confirmed IS NOT TRUE
      OR NEW.business_identity_confirmed IS NOT TRUE
      OR approved_document_count <> 3 THEN
      RAISE EXCEPTION
        'Courier validation requires legal identity, SIRET, address, three approved documents and both identity confirmations';
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.protect_courier_application_review_fields()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF auth.uid() IS NOT NULL AND NOT public.current_user_has_role('admin') THEN
    NEW.user_id := OLD.user_id;
    NEW.status := OLD.status;
    NEW.document_review_status := OLD.document_review_status;
    NEW.document_review_comment := OLD.document_review_comment;
    NEW.identity_name_confirmed := OLD.identity_name_confirmed;
    NEW.business_identity_confirmed := OLD.business_identity_confirmed;
    NEW.reviewed_by := OLD.reviewed_by;
    NEW.reviewed_at := OLD.reviewed_at;
    NEW.dispatch_priority_score := OLD.dispatch_priority_score;
  END IF;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.review_courier_application(
  target_application_id uuid,
  target_reviewer_id uuid,
  target_decision text,
  target_comment text,
  target_identity_name_confirmed boolean,
  target_business_identity_confirmed boolean,
  target_document_types text[]
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  application_row public.courier_applications%ROWTYPE;
  prelaunch_profile_id_value uuid;
  document_count integer;
  review_time timestamptz := now();
BEGIN
  IF current_user NOT IN ('postgres', 'service_role') THEN
    RAISE EXCEPTION 'Service role required';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = target_reviewer_id AND role = 'admin'
  ) THEN
    RAISE EXCEPTION 'Admin reviewer required';
  END IF;

  IF target_decision NOT IN ('approve', 'request_replacement', 'reject') THEN
    RAISE EXCEPTION 'Invalid review decision';
  END IF;

  IF target_decision <> 'approve'
     AND length(trim(coalesce(target_comment, ''))) < 5 THEN
    RAISE EXCEPTION 'A review comment is required';
  END IF;

  SELECT *
  INTO application_row
  FROM public.courier_applications
  WHERE id = target_application_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Courier application not found';
  END IF;

  SELECT id
  INTO prelaunch_profile_id_value
  FROM public.prelaunch_profiles
  WHERE user_id = application_row.user_id;

  IF target_decision = 'approve' THEN
    SELECT count(*)
    INTO document_count
    FROM public.courier_documents
    WHERE user_id = application_row.user_id
      AND document_type IN ('identity_front', 'identity_back', 'activity_proof');

    IF document_count <> 3
       OR target_identity_name_confirmed IS NOT TRUE
       OR target_business_identity_confirmed IS NOT TRUE THEN
      RAISE EXCEPTION 'Three documents and both identity confirmations are required';
    END IF;

    UPDATE public.courier_documents
    SET status = 'approved',
        review_comment = nullif(trim(coalesce(target_comment, '')), ''),
        reviewed_by = target_reviewer_id,
        reviewed_at = review_time
    WHERE user_id = application_row.user_id;

    UPDATE public.courier_applications
    SET status = 'validated',
        document_review_status = 'approved',
        document_review_comment = nullif(trim(coalesce(target_comment, '')), ''),
        identity_name_confirmed = true,
        business_identity_confirmed = true,
        reviewed_by = target_reviewer_id,
        reviewed_at = review_time,
        updated_at = review_time
    WHERE id = application_row.id;

    UPDATE public.profiles
    SET status = 'validated', updated_at = review_time
    WHERE id = application_row.user_id;

    UPDATE public.prelaunch_driver_details
    SET document_review_status = 'approved',
        document_review_comment = nullif(trim(coalesce(target_comment, '')), ''),
        reviewed_by = target_reviewer_id,
        reviewed_at = review_time
    WHERE prelaunch_profile_id = prelaunch_profile_id_value;
  ELSIF target_decision = 'request_replacement' THEN
    IF coalesce(array_length(target_document_types, 1), 0) = 0 THEN
      RAISE EXCEPTION 'Select at least one document to replace';
    END IF;

    UPDATE public.courier_documents
    SET status = 'replacement_requested',
        review_comment = trim(target_comment),
        reviewed_by = target_reviewer_id,
        reviewed_at = review_time
    WHERE user_id = application_row.user_id
      AND document_type = ANY(target_document_types);

    UPDATE public.courier_applications
    SET status = 'missing_documents',
        document_review_status = 'replacement_requested',
        document_review_comment = trim(target_comment),
        identity_name_confirmed = false,
        business_identity_confirmed = false,
        reviewed_by = target_reviewer_id,
        reviewed_at = review_time,
        updated_at = review_time
    WHERE id = application_row.id;

    UPDATE public.profiles
    SET status = 'missing_documents', updated_at = review_time
    WHERE id = application_row.user_id;

    UPDATE public.prelaunch_driver_details
    SET document_review_status = 'replacement_requested',
        document_review_comment = trim(target_comment),
        reviewed_by = target_reviewer_id,
        reviewed_at = review_time
    WHERE prelaunch_profile_id = prelaunch_profile_id_value;
  ELSE
    UPDATE public.courier_documents
    SET status = 'rejected',
        review_comment = trim(target_comment),
        reviewed_by = target_reviewer_id,
        reviewed_at = review_time
    WHERE user_id = application_row.user_id;

    UPDATE public.courier_applications
    SET status = 'rejected',
        document_review_status = 'rejected',
        document_review_comment = trim(target_comment),
        identity_name_confirmed = false,
        business_identity_confirmed = false,
        reviewed_by = target_reviewer_id,
        reviewed_at = review_time,
        updated_at = review_time
    WHERE id = application_row.id;

    UPDATE public.profiles
    SET status = 'rejected', updated_at = review_time
    WHERE id = application_row.user_id;

    UPDATE public.prelaunch_profiles
    SET status = 'rejected', updated_at = review_time
    WHERE id = prelaunch_profile_id_value;

    UPDATE public.prelaunch_driver_details
    SET document_review_status = 'rejected',
        document_review_comment = trim(target_comment),
        reviewed_by = target_reviewer_id,
        reviewed_at = review_time
    WHERE prelaunch_profile_id = prelaunch_profile_id_value;
  END IF;

  RETURN jsonb_build_object(
    'applicationId', application_row.id,
    'userId', application_row.user_id,
    'decision', target_decision,
    'reviewedAt', review_time
  );
END;
$$;

REVOKE ALL ON FUNCTION public.review_courier_application(uuid, uuid, text, text, boolean, boolean, text[]) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.review_courier_application(uuid, uuid, text, text, boolean, boolean, text[]) FROM authenticated;
GRANT EXECUTE ON FUNCTION public.review_courier_application(uuid, uuid, text, text, boolean, boolean, text[]) TO service_role;

-- Storage is private and direct object access is denied. Service-role signed
-- URLs are used instead, so no storage.objects policy is created here.
